### PR TITLE
feat: enhance running/testing capability and socket auto connect fix

### PR DESCRIPTION
**Pull request by T-kON99**
Makes running ACT easier and automatic via steam launch options, only for windows

Also fixed and made the socket to auto connect periodically (if failed initially)

### CODE REVIEW

**Comment by T-kON99** [comment]
@nyaoouo any chance of reviewing this PR? I just think it helps for using the parser whenever you open the game (I'm lazy to click)

**Comment by nyaoouo** [comment]
is there any difference between set steam start option as `"path\to\uac_start.cmd" && %Command%` then using your script?

**Comment by T-kON99** [comment]
yup there is, `uac_start.cmd` only starts `act_ws.py` , I just made it also opens `act_ws.html` and also open GBFR afterwards, of course I can just change `uac_start.cmd` but I think better to make a separate script for it?

**Comment by nyaoouo** [comment]
then `cd "/path/to/dir" && start "" "act_ws.html" && start "" " "uac_start.cmd" && %command%` ? i dont want to make so many files for user to confuse "which should i click"

**Comment by T-kON99** [comment]
yeah I can definitely add that to `uac_start.cmd` directly if that's preferable

**Comment by T-kON99** [comment]
I have updated and merged the changes to only affect `uac_start.cmd` feel free to review it once more!

**Pull request closed without merging**
